# Inserts a blank line between shell prompts
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[directory]
read_only = ""
style = "bold 245"

[git_branch]
symbol = "îœ¥ "

[git_status]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[python]
symbol  = "î˜† "

[nodejs]
disabled = true

[java]
symbol = "îœ¸ "
style = "bold 209"

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'
disabled = false

